Repository girlscript/feminist-bible-phase-2, pull requests merged in 2021-03, with the labels that each got.

#217 Avatar converted to Functional component
  frontend/package-lock.json
  frontend/src/components/Avatar/Avatar.jsx
Labels: Level1, gssoc21

#220 Update Footer.jsx
  frontend/src/components/Footer/Footer.jsx
Labels: frontend, gssoc21, level2

#227 Issue 221-10 digit mobile number
  backend/package-lock.json
  frontend/.ignore2/package-lock.json
  frontend/src/pages/Registration/Registration.jsx
Labels: Level0, gssoc21

#261 Issue-#257-Added Hover Effects for the cards
  frontend/src/components/BlogCard/blogcard.module.scss
  frontend/src/components/OrganisationCard/organisation-card.module.scss
  frontend/src/pages/Stories/stories.module.scss
Labels: Level1, gssoc21

#280 ci: separate development and production env
  backend/.env.example
  backend/README.md
  backend/config/dotenv.js
  backend/package.json
  backend/yarn.lock
Labels: Level2, gssoc21

#279 Create edit forum post controller function
  backend/controllers/forumController.js
  backend/routes/forumRoutes.js
Labels: Level1, gssoc21

#287 Correction of spellings
  README.md
Labels: Level0, gssoc21
