Repository girlscript/feminist-bible-phase-2, pull requests merged in 2021-04, with the labels that each got.

#296 Comments in routers and controllers for backend api
  backend/controllers/adminController.js
  backend/controllers/authController.js
  backend/controllers/forumController.js
  backend/controllers/orgController.js
  backend/controllers/projectController.js
  backend/controllers/storyController.js
  backend/controllers/userController.js
  backend/routes/adminRoutes.js
  backend/routes/authRoutes.js
  backend/routes/forumRoutes.js
  backend/routes/orgRoutes.js
  backend/routes/projectRoutes.js
  backend/routes/storyRoutes.js
  backend/routes/userRoutes.js
Labels: Level1, gssoc21

#303 Docs for auth, org and project API
  backend/api-docs/auth.rest
  backend/api-docs/org.rest
  backend/api-docs/project.rest
  backend/controllers/orgController.js
  backend/routes/orgRoutes.js
Labels: Level2, documentation, gssoc21

#309 added validate in adminModel and OrgModel file
  backend/database/models/adminModel.js
  backend/database/models/orgModel.js
Labels: Level0, gssoc21

#310 Docs for Admin and Organization API
  backend/api-docs/admin.rest
  backend/api-docs/user.rest
  backend/controllers/userController.js
Labels: Level2, documentation, gssoc21

#313 Docs for Forum and Story API
  backend/api-docs/admin.rest
  backend/api-docs/forum.rest
  backend/api-docs/org.rest
  backend/api-docs/story.rest
  backend/controllers/adminController.js
  backend/controllers/orgController.js
  backend/database/models/orgModel.js
Labels: Level2, documentation, gssoc21

#311 Organization Approval Flow Completed
  backend/api-docs/admin.rest
  backend/api-docs/forum.rest
  backend/api-docs/org.rest
  backend/api-docs/project.rest
  backend/api-docs/story.rest
  backend/api-docs/user.rest
  backend/controllers/adminController.js
  backend/controllers/authController.js
  backend/controllers/forumController.js
  backend/controllers/orgController.js
  backend/controllers/projectController.js
  backend/routes/adminRoutes.js
  backend/routes/forumRoutes.js
  backend/routes/orgRoutes.js
  backend/routes/projectRoutes.js
Labels: Level2, backend, gssoc21
